image:
  file: .gitpod.dockerfile

tasks:
  - init: sdk use java 14.0.2.j9-adpt
    command: cd javafx-app

ports:
  # used by virtual desktop and vnc, supports JavaFX
  - port: 6080
    onOpen: open-browser
  - port: 5900
    onOpen: ignore
  - port: 35900
    onOpen: ignore
